experiment:
  seed: 42
  total_timesteps: 5000000
  max_episode_steps: 500
  normalize_reward: false
  use_parallel: true
  n_envs: 10
  num_tasks: 10
  sac_disentangled_alpha: false  # true = disentangled alpha variant, false = baseline

eval:
  freq: 10000
  n_episodes: 20

checkpoint:
  freq: 25000

paths:
  models: ./metaworld_models
  logs: ./metaworld_logs

play:
  algorithm: SAC    # algorithm class used to load the model (SAC, DDPG, TD3)
  task_name: reach-v3
  num_episodes: 10
  render_mode: human

sac:
  learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005
  buffer_size: 2000000
  learning_starts: 1500
  batch_size: 512
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
  target_entropy: auto
  use_sde: false
  policy_kwargs:
    net_arch: [256, 256, 256]
    activation_fn: ReLU
    log_std_init: 0.0
